import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { AIRCRAFT_IDS } from "./aircraftIds";
import { getAircraftDefinition } from "./aircraftCatalog";
import { getFdmProfile } from "../jsbsim/fdmProfiles";
import {
  getSf50Variant,
  SF50_G3_PUBLISHED_PERFORMANCE,
  SF50_PUBLIC_MODEL_INPUTS,
  SF50_VARIANTS,
} from "./sf50Variants";

const readData = (path: string): string => readFileSync(
  new URL("../../../public/jsbsim-data/" + path, import.meta.url), "utf8",
);

/** Ignore package identity and comments, retaining every physical/FCS value. */
function sharedPhysics(xml: string): string {
  return xml
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/(<fdm_config\s+)name="[^"]+"/, '$1name="canonical-sf50"')
    .replace(/(<fileheader>[\s\S]*?<description>)[\s\S]*?(<\/description>)/, "$1$2")
    .trim();
}

function xmlNumber(xml: string, tag: string, unit: string): number {
  const match = xml.match(new RegExp(`<${tag} unit="${unit}">\\s*([^<]+)\\s*</${tag}>`));
  if (!match) throw new Error("Missing " + tag + " in " + unit);
  const value = Number(match[1]);
  if (!Number.isFinite(value)) throw new Error("Non-finite " + tag);
  return value;
}

describe("SF50 generation package contracts", () => {
  it("keeps the legacy G1 identity and separate original-G2/G3 profiles", () => {
    expect(SF50_VARIANTS.map(({ id, aircraftId, model, maxOperatingAltitudeFt }) => ({
      id, aircraftId, model, maxOperatingAltitudeFt,
    }))).toEqual([
      { id: "g1", aircraftId: "cirrus-vision-jet", model: "sf50", maxOperatingAltitudeFt: 28000 },
      { id: "g2", aircraftId: "cirrus-vision-jet-g2", model: "sf50-g2", maxOperatingAltitudeFt: 31000 },
      { id: "g3", aircraftId: "cirrus-vision-jet-g3", model: "sf50-g3", maxOperatingAltitudeFt: 31000 },
    ]);
    for (const variant of SF50_VARIANTS) {
      expect(getSf50Variant(variant.id)).toBe(variant);
      expect(getFdmProfile(variant.aircraftId)).toMatchObject({ model: variant.model, sf50VariantId: variant.id });
    }
    // The family UI alias must not silently become a separate evidence/model configuration.
    expect(() => getSf50Variant("g2+" as never)).toThrow(RangeError);
    expect(() => getSf50Variant("unknown" as never)).toThrow(RangeError);
  });

  it.each(["g2", "g3"] as const)("keeps the generated %s package synchronized with canonical G1 physics", (id) => {
    const variant = getSf50Variant(id);
    const canonical = readData("aircraft/sf50/sf50.xml");
    const generated = readData(`aircraft/${variant.model}/${variant.model}.xml`);
    expect(generated).toContain(`<fdm_config name="${variant.model}" release="ALPHA"`);
    expect(generated).toContain("GENERATED by scripts/build-sf50-variants.mjs. Do not edit this copy.");
    expect(generated).toContain(`${variant.label}: shared G1-based development physics, not calibrated for this generation.`);
    expect(sharedPhysics(generated)).toBe(sharedPhysics(canonical));
  });

  it("routes each manifest package to its own model and the shared turbine/direct thruster", () => {
    const manifest = JSON.parse(readData("manifest.json")) as {
      files: string[];
      aircraft: Record<string, string[]>;
    };
    expect(Object.keys(manifest.aircraft).sort()).toEqual([...AIRCRAFT_IDS].sort());
    expect(manifest.files).toEqual(manifest.aircraft["cessna-172"]);
    for (const variant of SF50_VARIANTS) {
      const modelPath = `aircraft/${variant.model}/${variant.model}.xml`;
      expect(manifest.aircraft[variant.aircraftId]).toEqual([
        modelPath, "engine/fj33_5a.xml", "engine/direct.xml",
      ]);
      const model = readData(modelPath);
      expect([...model.matchAll(/<engine\s+file="([^"]+)"/g)].map((match) => match[1])).toEqual(["fj33_5a"]);
      expect([...model.matchAll(/<thruster\s+file="([^"]+)"/g)].map((match) => match[1])).toEqual(["direct"]);
      expect(model).toMatch(/<engine file="fj33_5a">\s*<feed>0<\/feed>/);
    }
    expect(readData("engine/fj33_5a.xml")).toContain('<turbine_engine name="FJ33-5A">');
    expect(readData("engine/direct.xml")).toContain('<direct name="Direct">');
  });

  it("retains sourced baseline facts and applies them to every package without reconciling nominal rounding", () => {
    expect(SF50_PUBLIC_MODEL_INPUTS).toMatchObject({
      ratedThrustLbf: 1846, usableFuelLb: 2001, usableFuelUsGal: 296,
      nominalFuelDensityLbPerUsGal: 6.76, wingAreaSqFt: 195.7, wingMacIn: 62.2,
    });
    expect(SF50_PUBLIC_MODEL_INPUTS.sources.engineAndFuel).toMatchObject({
      document: "31452-001", pdfPage: 23, printedPage: "1-7",
      sha256: "d83e904dbd6bc3656321c93d793166d4a5c6eddf81852b15767e5c336fc23949",
    });
    expect(SF50_PUBLIC_MODEL_INPUTS.sources.wingMac).toMatchObject({
      document: "AMM 6-00-2, 2018-07-09, reproduced in WPR20FA051", pdfPage: 13, figure: 15,
    });
    expect(xmlNumber(readData("engine/fj33_5a.xml"), "milthrust", "LBS")).toBe(1846);
    for (const variant of SF50_VARIANTS) {
      const model = readData(`aircraft/${variant.model}/${variant.model}.xml`);
      expect(xmlNumber(model, "capacity", "LBS")).toBe(2001);
      expect(xmlNumber(model, "chord", "FT") * 12).toBeCloseTo(62.2, 10);
      expect(xmlNumber(model, "wingarea", "FT2")).toBe(195.7);
    }
  });

  it("keeps shared presentation and provisional physics distinct from generation-specific fidelity", () => {
    const g1 = getAircraftDefinition("cirrus-vision-jet");
    for (const variant of SF50_VARIANTS) {
      expect(variant.physicsStatus).toBe("development-baseline");
      expect(variant.independentlyValidated).toBe(false);
      expect(getAircraftDefinition(variant.aircraftId).lods).toEqual(g1.lods);
      expect(variant.sources.length).toBeGreaterThan(0);
    }
    expect(getSf50Variant("g2").evidenceScope).toContain("G2+ updated-thrust tables are kept separate");
    expect(SF50_G3_PUBLISHED_PERFORMANCE).toMatchObject({
      conditionsKnown: false, eligibleForCalibration: false, eligibleForIndependentValidation: false,
    });
  });
});
